# DO NOT EDIT this file. It is set up in such a way that if you make any edits,
# the test cases may change resulting in a broken local autograder.

# Imports
from test_ctc import CTCTest
from test_search import SearchTest


############################################################################################
########################## Test Cases - DO NOT EDIT ########################################
############################################################################################

if __name__ == "__main__":
    ctc_test = CTCTest()
    ctc_test_outcome = ctc_test.run_test()

    search_test = SearchTest()
    search_test_outcome = search_test.run_test()
