_wandb:
    value:
        cli_version: 0.21.0
        e:
            xuuf7rrr9tpu20nk8hs0vuodlstiytmz:
                codePath: q1_q2_classification/train_q1.py
                codePathLocal: q1_q2_classification/train_q1.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "514909536256"
                        used: "464595808256"
                email: khjune29@gmail.com
                executable: /home/alice/anaconda3/envs/whisper/bin/python
                gpu: NVIDIA GeForce RTX 3080 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3080 Laptop GPU
                      uuid: GPU-c968885d-381b-cd8b-d69d-46b528a870ec
                host: SnowyWonderland
                memory:
                    total: "33340645376"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/alice/Doughnut/recitations/basics/visual_learning_p1/q1_q2_classification/train_q1.py
                python: CPython 3.10.16
                root: /home/alice/Doughnut/recitations/basics/visual_learning_p1
                startedAt: "2025-07-09T13:27:14.235457Z"
                writerId: xuuf7rrr9tpu20nk8hs0vuodlstiytmz
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
            "4": 3.10.16
            "5": 0.21.0
            "8":
                - 2
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
